image: python:3.8

stages:
  - test
  - train
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - data/
    - models/

before_script:
  - python -V
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

test:
  stage: test
  script:
    - export CUDA_VISIBLE_DEVICES=""
    - pytest tests/test_model.py -v --cov=.
  artifacts:
    reports:
      coverage: coverage.xml

train:
  stage: train
  script:
    # Modify training parameters for CI environment
    - |
      sed -i 's/num_epochs=20/num_epochs=1/g' eva3_session_6_assignment_.py
      sed -i 's/batch_size=32/batch_size=16/g' eva3_session_6_assignment_.py
    # Run training
    - python eva3_session_6_assignment_.py
  artifacts:
    paths:
      - models/
      - augmented_samples/
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying model..."
    # Add model deployment steps here
  only:
    - main
  dependencies:
    - train 