image: python:3.8

stages:
  - setup
  - train
  - test
  - upload

setup:
  stage: setup
  script:
    - python -V
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  cache:
    paths:
      - .pip-cache/

train:
  stage: train
  script:
    # Quick training for CI
    - |
      sed -i 's/num_epochs=20/num_epochs=1/g' eva3_session_6_assignment_.py
      sed -i 's/batch_size=32/batch_size=16/g' eva3_session_6_assignment_.py
    - python eva3_session_6_assignment_.py
  cache:
    paths:
      - data/
      - models/

test:
  stage: test
  script:
    - export CUDA_VISIBLE_DEVICES=""
    - pytest tests/test_model.py -v

upload:
  stage: upload
  script:
    - echo "Uploading trained model..."
    - ls models/
  artifacts:
    paths:
      - models/*.pth
      - augmented_samples/
    expire_in: 1 week
  only:
    - main